### ISSUE TITLE
Improving th UI of page

### ISSUE THREAD

**Issue by Nidhi1k** [Zack-Dx/Twitter-Landing-Page#10]
The page UI can be improved the image and sign in part are both not looking good . And footer is over lapping .

**Comment by Zack-Dx** [comment]
@Nidhi1k go ahead.

**Comment by Nuel-Eneji** [comment]
Please assign it to me 
Thanks

**Comment by Zack-Dx** [comment]
> Please assign it to me Thanks

@Nuel-Eneji it's already assigned u can try making it responsive! make a new issue.

**Comment by Arceus-sj** [comment]
Can I work on the UI and responsive buttons?
