### ISSUE TITLE
Updated the UI (Page Layout & Buttons)

### ISSUE THREAD

**Issue by Arceus-sj** [Zack-Dx/Twitter-Landing-Page#17]
Please assign me this issue.

**Comment by Zack-Dx** [comment]
@Arceus-sj done.

**Comment by Arceus-sj** [comment]
Here is my updated version of your web page.
![issue_1](https://user-images.githubusercontent.com/71997730/193876988-a8fc2034-852b-4f66-9f5e-ee8837e97013.JPG)

**Comment by Arceus-sj** [comment]
I make a PR. Please check it out.
