### ISSUE TITLE
Responsive layout support

### ISSUE THREAD

**Issue by hientranea** [Zack-Dx/Twitter-Landing-Page#2]
Now the landing page is broken at some breakpoints
![Screen Shot 2022-10-04 at 11 43 08 AM](https://user-images.githubusercontent.com/40749524/193736050-a7830c64-740e-4e81-be47-482cb0ad40df.png)

**Comment by hientranea** [comment]
@Zack-Dx Could I work on this issue? If yes, please tag this issue with `hacktoberfest` tag. Thanks

**Comment by Zack-Dx** [comment]
> @Zack-Dx Could I work on this issue? If yes, please tag this issue with `hacktoberfest` tag. Thanks

Sure mate.

**Comment by hientranea** [comment]
@Zack-Dx  Please help me review this PR https://github.com/Zack-Dx/Twitter-Landing-Page/pull/3
