### ISSUE TITLE
Add a favicon to the site

### ISSUE THREAD

**Issue by devnullone** [Zack-Dx/Twitter-Landing-Page#37]
Favicon is important for websites, it is good for branding and visibility!

**Comment by Zack-Dx** [comment]
> Favicon is important for websites, it is good for branding and visibility!

@devnullone Surely. Try to use a responsive one!

**Comment by devnullone** [comment]
> > Favicon is important for websites, it is good for branding and visibility!
> 
> @devnullone Surely. Try to use a responsive one!

Yes @Zack-Dx, I just submit a PR.
Cheers!
