### ISSUE TITLE
Adding light and dark mode

### ISSUE THREAD

**Issue by theashu02** [Zack-Dx/Twitter-Landing-Page#4]
Placing a toggle button to switch between light & dark mode.
@Zack-Dx  please assign me this under Hacktoberfest2022

**Comment by Zack-Dx** [comment]
> Placing a toggle button to switch between light & dark mode. @Zack-Dx please assign me this under Hacktoberfest2022

done mate.

**Comment by Khushi-dev-1822** [comment]
hey, Can I work on this?

**Comment by Zack-Dx** [comment]
> hey, Can I work on this?

@Khushi-dev-1822 sure! welcome

**Comment by Khushi-dev-1822** [comment]
> > hey, Can I work on this?
> 
> @Khushi-dev-1822 sure! welcome

Thank you :)

**Comment by Khushi-dev-1822** [comment]
Hey, I have added toggle functionality.

**Comment by Khushi-dev-1822** [comment]
Hey, will this count in hacktoberfest??
