### ISSUE TITLE
link style.css properly!

### ISSUE THREAD

**Issue by Zack-Dx** [Zack-Dx/Twitter-Landing-Page#49]

**Comment by amanchoudhary18** [comment]
Assign it to me

**Comment by Zack-Dx** [comment]
@amanchoudhary18 done.

**Comment by AadeshKabra** [comment]
Can i work on this?

**Comment by amanchoudhary18** [comment]
Give a little bit of description. I can see the CSS linked fine.

**Comment by Zack-Dx** [comment]
> Give a little bit of description. I can see the CSS linked fine.



> Give a little bit of description. I can see the CSS linked fine.

put index.html  and css out from the folder so that it could recognise Github pages properly.

**Comment by Zack-Dx** [comment]
> Can i work on this?
Sorry mate u can fix other issues.
