### ISSUE TITLE
Making the page more like current twitter landing page & making some other minor changes....

### ISSUE THREAD

**Issue by ojninja16** [Zack-Dx/Twitter-Landing-Page#5]
I would like to make some improvements to the UI and more like the original landing page...

**Comment by Zack-Dx** [comment]
@ojninja16 go ahead!

**Comment by ojninja16** [comment]
thanks!!! on it...

**Comment by Zack-Dx** [comment]
> thanks!!! on it...

it's a bit broken for the desktop can u fix that too? @ojninja16

**Comment by ojninja16** [comment]
Yeah sure.....

**Comment by Nidhi1k** [comment]
@Zack-Dx 
I have created a pull request have a look

**Comment by Utsab5** [comment]
Hi @Zack-Dx ,
I also want to work on this.
Can you assign me too.

**Comment by Zack-Dx** [comment]
@Utsab5 done.

**Comment by Utsab5** [comment]
thanks

**Comment by Dhairyash-1** [comment]
Hey, @Zack-Dx  I want to make it more responsive and make some changes in the footer can you assign me?

**Comment by Zack-Dx** [comment]
> Hey, @Zack-Dx I want to make it more responsive and make some changes in the footer can you assign me?

sure @Dhairyash-1

**Comment by Dhairyash-1** [comment]
@Zack-Dx Thanks

**Comment by Zack-Dx** [comment]
> @Zack-Dx Thanks

throw a pr once done.

**Comment by Utsab5** [comment]
@Zack-Dx ,
I have made a pr, 
Please have a look.
