### ISSUE TITLE
Can I add CheatSheet Of HTML, CSS, JAVASCRIPT

### ISSUE THREAD

**Issue by nihal-soni** [Zack-Dx/Twitter-Landing-Page#52]
Hey' 
I'm Nihal and if want 
I would like to add Cheatsheet  to your repository
This will be very beneficial for beginner

**Comment by Zack-Dx** [comment]
> Hey' I'm Nihal and if want I would like to add Cheatsheet to your repository This will be very beneficial for beginner

Sorry, but this wont add any such relatable value to the landing page. Thank You!
