### ISSUE TITLE
Including web standards in the project

### ISSUE THREAD

**Issue by lucalves** [Zack-Dx/Twitter-Landing-Page#59]
Hello all!

I noticed the need to adapt and improve the project in some points:

- Images without the `alt` tag for accessibility;
- Some repeated images;
- Improvements in `assets` file names;
- Indent of the `.css` file;
- Conversion of the favicon file from `.png` to `.ico`;

I'll open a Pull Request for that :)

**Comment by Zack-Dx** [comment]
@lucalves Sure go ahead.
