### ISSUE TITLE
Image should be full height

### ISSUE THREAD

**Issue by Pranshu1902** [Zack-Dx/Twitter-Landing-Page#6]
The image should cover the entire screen height.
![image](https://user-images.githubusercontent.com/70687348/193785378-9b72d0e1-ccab-447d-a5a8-0cb9cbf7433f.png)

Also, improve the button(login, signup) hover effect duration time.
@Zack-Dx If you find this a valid issue then please assign it to me.

**Comment by Zack-Dx** [comment]
@Pranshu1902 nope! sorry but if want to contribute try making it responsive at broken parts.
