### ISSUE TITLE
Make responsive buttons in mobile view

### ISSUE THREAD

**Issue by Pranshu1902** [Zack-Dx/Twitter-Landing-Page#7]
The buttons are going outside the screen for mobile view
![image](https://user-images.githubusercontent.com/70687348/193787900-0c552bfe-04a9-4afe-849a-85574181f47d.png)

@Zack-Dx  Please assign this issue to me, I would love to make it better

**Comment by Zack-Dx** [comment]
@Pranshu1902 go ahead.

**Comment by Pranshu1902** [comment]
On it

**Comment by Nidhi1k** [comment]
can i do it ?

**Comment by Zack-Dx** [comment]
> can i do it ?

@Nidhi1k u can fix the responsiveness. If u want to raise an issue!

**Comment by Zack-Dx** [comment]
@Nidhi1k u can try too.

**Comment by Nidhi1k** [comment]
😀

**Comment by Nidhi1k** [comment]
I have opened a new issue have a look on it .

**Comment by Zack-Dx** [comment]
> I have opened a new issue have a look on it .

@Nidhi1k assigned it to you.

**Comment by Pranshu1902** [comment]
@Zack-Dx Hi, you closed my PR #8 . What happened, please reopen it so that I can update the branch so that it can be merged. Or do you want me to create a new PR?

**Comment by Zack-Dx** [comment]
> @Zack-Dx Hi, you closed my PR #8 . What happened, please reopen it so that I can update the branch so that it can be merged. Or do you want me to create a new PR? Thank you.

make a new pr and update it all there and make sure u check all your changes locally.
