### ISSUE TITLE
Fix responsiveness for tablets!

### ISSUE THREAD

**Issue by Zack-Dx** [Zack-Dx/Twitter-Landing-Page#74]

**Comment by Gurvir-Sandhar** [comment]
can i take this issue?

**Comment by Zack-Dx** [comment]
> can i take this issue?

@Gurvir-Sandhar done.

**Comment by Gurvir-Sandhar** [comment]
@Zack-Dx What exactly needs to be fixed? Right now, the media query for tablets sets the flex-direction to reverse column.

**Comment by Zack-Dx** [comment]
> @Zack-Dx What exactly needs to be fixed? Right now, the media query for tablets sets the flex-direction to reverse column.

just check that image is facing an overflow for ipads.

**Comment by ImanHasan** [comment]
@Zack-Dx can i fix this issue?

**Comment by Satakshijain** [comment]
Can you please assign this issue to me

**Comment by Dhairyash-1** [comment]
Hey, @Zack-Dx  I have just fixed the overflow of image and made buttons more responsive. I have made a pull request have a look.

**Comment by Zack-Dx** [comment]
@Dhairyash-1 please don't deleted your forked repo before getting it merged.

**Comment by Dhairyash-1** [comment]
@Zack-Dx can I create once again this pr?

**Comment by Zack-Dx** [comment]
> @Zack-Dx can I create once again this pr?

Sure.

**Comment by Dhairyash-1** [comment]
@Zack-Dx I have created the pr once again have a look.

**Comment by Zack-Dx** [comment]
> @Zack-Dx I have created the pr once again have a look.

@Dhairyash-1 Great Work!
