### ISSUE TITLE
Hover transitions and removal of borders on hover

### ISSUE THREAD

**Issue by marsian83** [Zack-Dx/Twitter-Landing-Page#75]
**The Issue**
Hovering on the buttons immediately changes their colors instead of a slight transition which is on most professional websites including the original twitter landing page. Also the borders remain on hover instead of the entire button changing color which should not be the case. 

**Expected Behaviour**
Hovering on any button must have a slight transition between color changes and other effects
The borders on the buttons must also either change color or not be visible on hover.

**Screenshots**
![Screenshot (9)](https://user-images.githubusercontent.com/114365550/194216806-83300d55-3511-463f-9a54-653f1cbfa3be.png)
![Screenshot (10)](https://user-images.githubusercontent.com/114365550/194216815-b5ef3af8-6ff3-44b3-9fb3-90e230d3fa16.png)

**Additional**
I reckon I could fix this, please assign this issue to me under hactoberfest

**Comment by marsian83** [comment]
I'd like to work on this myself, please assign this to me under hacktoberfest @Zack-Dx

**Comment by Zack-Dx** [comment]
> I'd like to work on this myself, please assign this to me under hacktoberfest @Zack-Dx

@marsian83 done mate.

**Comment by marsian83** [comment]
#76 does this suffice?
