### ISSUE TITLE
Sign in and Sign up page 

### ISSUE THREAD

**Issue by Shivangbhatnagar237** [Zack-Dx/Twitter-Landing-Page#78]
### Create a Sign-in page for people who already have an account and a Sign-up page for the people who don't have an account.
![twit1](https://user-images.githubusercontent.com/47966497/194246078-54725c7d-6fc4-4a8c-8491-fd10a2870bf2.PNG)
![twit2](https://user-images.githubusercontent.com/47966497/194246094-b535301f-23ad-407d-b8df-e512964f5aa3.PNG)

**Comment by Shivangbhatnagar237** [comment]
@Zack-Dx please assign this issue to me under hacktoberfest, I can solve it.

**Comment by Zack-Dx** [comment]
@Shivangbhatnagar237 done.

**Comment by Shivangbhatnagar237** [comment]
Thanks ❤
