### ISSUE TITLE
Adding small logos of twitter on background.

### ISSUE THREAD

**Issue by Akashsingh9936** [Zack-Dx/Twitter-Landing-Page#9]
This is a non code contribution for editing the background image,
@Zack-Dx please assign me this under v

**Comment by Zack-Dx** [comment]
@Akashsingh9936 try to share ss of your image.

**Comment by utkarshmishra27** [comment]
Please assign this to me

**Comment by trisha-thakur** [comment]
can you assign this issue to me

**Comment by Zack-Dx** [comment]
@devUT27 @trisha-thakur  u both can contribute but whoever comes first I'll merge. Thank You!

**Comment by sumitbaroniya** [comment]
Please assign me this issue. I would like to contribute in it.

**Comment by Zack-Dx** [comment]
> Please assign me this issue. I would like to contribute in it.

@sumitbaroniya sure! welcome

**Comment by sakshi025** [comment]
@Zack-Dx please assign me this issue. I would like to contribute in it

**Comment by sakshi025** [comment]
@Zack-Dx favicon is still needed to be added. If yes can i add this ?

**Comment by aparna03dubey** [comment]
@Zack-Dx Please assign this issue to me for contribution.

**Comment by Akashsingh9936** [comment]
@Zack-Dx Accidentally got un-assigned.
Please assign again

**Comment by Zack-Dx** [comment]
@Akashsingh9936 @aparna03dubey @sakshi025 if yes u guys want to add favicon using favicon generator and make a pull req whoever does it first. Thank YOU!
